# Generated by Django 4.1.3 on 2022-12-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
