# Generated by Django 4.1.3 on 2022-12-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_familiar_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar_nacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('relacion', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
